### ISSUE TITLE
DBC File placement

### ISSUE THREAD

**Issue by BlakeFreer** [macformula/racecar#154]
Our CAN DBC files are currently _all_ stored under `firmware/dbcs`. Sharing this folder means it is filled with unrelated DBC files, for example `demo.dbc` for the Demo/Can projects is mixed with the actual EV5 `pt.dbc` and `veh.dbc` files.

```text
firmware/
├── dbcs/
│   ├── demo.dbc
│   ├── pt.dbc
│   └── veh.dbc
└── projects/
    ├── DemoCanReceiver/
    ├── DemoCanTransmitter/
    ├── LVController/
    ├── FrontController/
    └── TMS/
```

It also means that all DBC files must have different names which could become a problem as more versions are created. We cannot maintain the existing `veh.dbc` file and update it for the new season without changing a file name. This makes it difficult to maintain consistent naming across projects.

One solution is placing the DBC files in a project. However, projects (currently) correspond to a single ECU and multiple ECUs need access to the DBCs (since DBC files are the inter-ECU messaging protocol). This solution would incorrectly imply that one project owns the DBC.

Another solution (which ~~will be~~ was enabled by #113) is to organize the _projects_ into folders which the DBC files. This makes a _lot_ of sense given that the DBCs connect multiple ECU projects, so these projects should be combined in a folder. This could look like

```text
firmware/
└── projects/
    ├── DemoCan/
    │   ├── Receiver/
    │   ├── Transmitter/
    │   └── demo.dbc
    └── EV5/
        ├── LVController/
        ├── FrontController/
        ├── TMS/
        ├── pt.dbc
        └── veh.dbc
```

**Comment by samparent97** [comment]
Upon making this change, consider implementing this change https://github.com/macformula/hil/issues/84.
