### ISSUE TITLE
Build System: Add support for source files in mcal/shared folders

### ISSUE THREAD

**Issue by samparent97** [macformula/racecar#35]
Currently all method definitions must be in class's header file.

**Comment by BlakeFreer** [comment]
This will require the developer to add the required source files to the project-level CMakeLists.txt (like [this one](https://github.com/macformula/racecar/blob/main/firmware/projects/DemoProject/main.cc)). I support the change but want to note this.

**Comment by BlakeFreer** [comment]
No changes to the build system are required. The code file can be added as a source in the project CMake file as follows:

```CMake
target_sources(main
PRIVATE
	main.cc
	${CMAKE_SOURCE_DIR}/shared/path/to/code.c
)
```

Note the use of `CMAKE_SOURCE_DIR` and not `CMAKE_CURRENT_SOURCE_DIR`. CURRENT refers to the directory containing the CMakeLists.txt file (in this case, `firmware/projects/DemoProject`), while `CMAKE_SOURCE_DIR` is the directory of the top-level CMake file, which is `firmware`, which is desired when locating shared code files.
